version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 10gicwaves
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    build: ./backend
    container_name: nodejs_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://root:10gicwaves@mongodb:27017/monitoring?authSource=admin
      - BREVO_API_KEY=${BREVO_API_KEY}  # Add this line to pull the key from host OS env variable
    volumes:
      - ./backend:/usr/src/app
      - ./logs:/logs  # This maps the container's /logs to your host's ./logs directory
    depends_on:
      - mongodb

  landing:
    image: nginx:alpine
    container_name: landing-page
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./landing:/usr/share/nginx/html

  controlpanel:
    image: nginx:alpine
    container_name: control-panel
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./control-panel:/usr/share/nginx/html

  mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      depends_on:
        - mongodb
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: 10gicwaves
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_BASICAUTH_USERNAME: root                # Mongo Express login username
        ME_CONFIG_BASICAUTH_PASSWORD: 10gicwaves 
      ports:
        - "8082:8081"